FROM node:20-alpine

# Instala OpenSSL e outras dependências necessárias para o Prisma
RUN apk add --no-cache openssl libc6-compat

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Bypass checksum validation if Prisma's binary server is down
ENV PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
