-- Add new values to AuditAction enum
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_LIST';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CAMPAIGN_LIST';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CAMPAIGN_EDIT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MESSAGE_LIST';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUDIT_VIEW';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SYSTEM_VIEW';
